<?php
$secretkey         = "grandMASTercP4YfrDUysh2rWjeT0ZXt";
$authenticatedUser = '';

//ROLES
const ROLE_SUPERADMIN        = "1";
const ROLE_ACCOUNTS_MANAGER  = "2";
const ROLE_SALES_MANAGER     = "3";
const ROLE_SALES_EXECUTIVE   = "4";
const ROLE_WAREHOUSE_MANAGER = "5";


//Document Number Prefix
const PREFIX_QUOTATION               = "GM-Q-";
const PREFIX_SALESORDER              = "GM-SO-";
const PREFIX_INVOICE                 = "GM-INV-";
const PREFIX_CONSULTATION_QUOTATION  = "IT-Q-";
const PREFIX_CONSULTATION_PROPOSAL  = "IT-P-";
const PREFIX_CONSULTATION_SMA  = "IT-SMA-";
const PREFIX_CONSULTATION_SALESORDER = "IT-SO-";
const PREFIX_CONSULTATION_PROFORMA_INVOICE = "IT-P-INV-";
const PREFIX_CONSULTATION_PROJECT = "IT-PRJ-";
const PREFIX_CONSULTATION_PROJECT_TASK = "IT-TASK-";
const PREFIX_CONSULTATION_INVOICE    = "IT-INV-";
const PREFIX_RFP                     = "GM-RFP-";
const PREFIX_PO                      = "GM-PO-";
const PREFIX_RFP_CONSULTATION                     = "IT-RFP-";
const PREFIX_PO_CONSULTATION                      = "IT-PO-";
const PREFIX_TRANSFER = "GM-WHT-";
const PREFIX_SHIPMENT = "GM-WH-";
const PREFIX_GDN = "GM-GDN-";
const PREFIX_SDN = "IT-SDN-";


//Document Statuses
//Quotations

const QUOTATION_STATUS_NEW                                = 'NEW';
const QUOTATION_STATUS_AWAITING_APPROVAL                  = 'AWAITING APPROVAL';
const QUOTATION_STATUS_APPROVED                           = 'APPROVED';
const QUOTATION_STATUS_REJECTED                           = 'REJECTED';
const QUOTATION_STATUS_SENT_TO_CUSTOMER                   = 'SENT TO CUSTOMER';
const QUOTATION_STATUS_CUSTOMER_ACCEPTED                  = 'CUSTOMER ACCEPTED';
const QUOTATION_STATUS_CUSTOMER_REJECTED                  = 'CUSTOMER REJECTED';
const QUOTATION_STATUS_CONFIRMED                          = 'CONFIRMED';
const QUOTATION_STATUS_CANCELLED                          = 'CANCELLED';
const QUOTATION_STATUS_AWAITING_SALES_MANAGER_SO_APPROVAL = 'AWAITING SALES MANAGER SO APPROVAL';
const QUOTATION_STATUS_SALES_MANAGER_SO_REJECTED          = 'SALES MANAGER SO REJECTED';
const QUOTATION_STATUS_AWAITING_ACCOUNTANT_SO_APPROVAL    = 'AWAITING ACCOUNTANT SO APPROVAL';
const QUOTATION_STATUS_ACCOUNTANT_SO_REJECTED             = 'ACCOUNTANT SO REJECTED';
const QUOTATION_STATUS_SO_APPROVED                        = 'SO APPROVED';
const QUOTATION_STATUS_PROFORMA_ISSUED                    = 'PROFORMA INVOICE ISSUED';
const SALESORDER_STATUS_CONFIRMED = 'CONFIRMED';
const SALESORDER_STATUS_CANCELLED                          = 'CANCELLED';

const ORDER_STATUS_NEW                                = 'NEW';
const ORDER_STATUS_AWAITING_APPROVAL                  = 'AWAITING APPROVAL';
const ORDER_STATUS_APPROVED                           = 'APPROVED';
const ORDER_STATUS_REJECTED                           = 'REJECTED';
const ORDER_STATUS_ACCOUNTANT_REJECTED                = 'ACCOUNTANT REJECTED';
const ORDER_STATUS_ACCOUNTANT_APPROVED                = 'ACCOUNTANT APPROVED';
const ORDER_STATUS_SENT_TO_CUSTOMER                   = 'SENT TO CUSTOMER';
const ORDER_STATUS_CUSTOMER_ACCEPTED                  = 'CUSTOMER ACCEPTED';
const ORDER_STATUS_CUSTOMER_REJECTED                  = 'CUSTOMER REJECTED';


const STATUS_GENERIC_APPROVED = 'APPROVED';
const STATUS_GENERIC_REJECTED = 'REJECTED';
const STATUS_GENERIC_NEUTRAL  = 'NEUTRAL';

//Request for Proposal
const RFP_STATUS_NEW                          = 'NEW';
const RFP_STATUS_PROCUREMENT_MANAGER_APPROVAL = 'AWAITING PROCUREMENT MANAGER APPROVAL';
const RFP_STATUS_PROCUREMENT_MANAGER_APPROVED = 'PROCUREMENT MANAGER APPROVED';
const RFP_STATUS_PROCUREMENT_MANAGER_REJECTED = 'PROCUREMENT_MANAGER_REJECTED';
const RFP_STATUS_SENT_TO_SUPPLIER             = 'RFP SENT TO SUPPLIER';
const RFP_STATUS_PO_CREATED = 'PO CREATED';

//Invoice
const INVOICE_STATUS_NEW                          = 'NEW';
const INVOICE_STATUS_ACCOUNTANT_APPROVAL = 'AWAITING ACCOUNTANT APPROVAL';
const INVOICE_STATUS_ACCOUNTANT_APPROVED = 'ACCOUNTANT APPROVED';
const INVOICE_STATUS_ACCOUNTANT_REJECTED = 'ACCOUNTANT REJECTED';
const INVOICE_STATUS_SENT_TO_CUSTOMER             = 'SENT TO CUSTOMER';

//Bills of Lading
const GDN_STATUS_NEW                            = 'NEW';
const GDN_STATUS_PROCUREMENT_MANAGER_APPROVAL = 'AWAITING PROCUREMENT MANAGER APPROVAL';
const GDN_STATUS_PROCUREMENT_MANAGER_APPROVED = 'PROCUREMENT MANAGER APPROVED';
const GDN_STATUS_PROCUREMENT_MANAGER_REJECTED = 'PROCUREMENT_MANAGER_REJECTED';
const GDN_CREATED             = 'GDN NUMBER GENERATED';

//Warehouse Transfer
const TRANSFER_STATUS_NEW                          = 'NEW';
const TRANSFER_STATUS_PROCUREMENT_MANAGER_APPROVAL = 'AWAITING PROCUREMENT MANAGER APPROVAL';
const TRANSFER_STATUS_PROCUREMENT_MANAGER_APPROVED = 'PROCUREMENT MANAGER APPROVED';
const TRANSFER_STATUS_PROCUREMENT_MANAGER_REJECTED = 'PROCUREMENT_MANAGER_REJECTED';
const TRANSFER_STATUS_SENT_TO_PICK_AND_PACK = 'SENT TO PICK AND PACK';

//Order WH Status
const ORDER_WH_STATUS_RETURNED = 'RETURNED';
const ORDER_WH_STATUS_ALLOCATED = 'ALLOCATED';
const ORDER_WH_STATUS_STAGED = 'STAGED';
const ORDER_WH_STATUS_RESERVED = 'RESERVED';
const ORDER_WH_STATUS_PARTIALLY_RESERVED = 'PARTIALLY RESERVED';
const ORDER_WH_STATUS_READY = 'READY';
const ORDER_WH_STATUS_PARTIALLY_READY = 'PARTIALLY READY';
const ORDER_WH_STATUS_SHIPPED = 'SHIPPED';

//Purchase Order
const PO_STATUS_NEW                                  = 'NEW';
const PO_STATUS_AWAITING_SPAREPARTS_MANAGER_APPROVAL = 'AWAITING SPAREPARTS MANAGER APPROVAL';
const PO_STATUS_SPAREPARTS_MANAGER_APPROVED          = 'SPAREPARTS MANAGER APPROVED';
const PO_STATUS_SPAREPARTS_MANAGER_REJECTED          = 'SPAREPARTS MANAGER REJECTED';
const PO_STATUS_AWAITING_ACCOUNTANT_APPROVAL         = 'AWAITING ACCOUNTANT APPROVAL';
const PO_STATUS_ACCOUNTANT_APPROVED                  = 'ACCOUNTANT APPROVED';
const PO_STATUS_ACCOUNTANT_REJECTED                  = 'ACCOUNTANT REJECTED';
const PO_STATUS_SENT_TO_SUPPLIER                     = 'PO SENT TO SUPPLIER';
const PO_STATUS_GOODS_RECEIVED                     = 'GOODS RECEIVED';
const PO_STATUS_SUPPLIER_INVOICE_ATTACHED            = 'SUPPLIER INVOICE ATTACHED';


//Operations Types - used for Keydocument history records
const OT_NEW_QUOTATION                  = 'NEW QUOTATION';
const OT_SAVE_QUOTATION                 = 'SAVE QUOTATION';
const OT_SAVE_QUOTATION_WITH_ATTACHMENT = 'SAVE QUOTATION WITH ATTACHMENT';

const OT_NEW_ORDER                  = 'NEW ORDER';

//Operations Types - used for Project history records
const OT_NEW_PROJECT                  = 'NEW PROJECT';
const OT_EDIT_PROJECT                 = 'EDIT PROJECT';

const OT_NEW_TASK                  = 'NEW TASK';
const OT_EDIT_TASK                 = 'EDIT TASK';
const OT_MARK_TASK_DONE            = 'MARK TASK AS DONE';
const OT_DELETE_TASK               = 'DELETE TASK';

//Operations Types - used for Sparepart history records
const OT_NEW_SPAREPART                  = 'NEW SPAREPART';
const OT_EDIT_SPAREPART                 = 'EDIT SPAREPART';

const OT_SPAREPART_QUANTITY_CHANGE                 = 'SPAREPART QUANITY CHANGE';

//Operations Types - used for Machine history records
const OT_NEW_MACHINE                  = 'NEW MACHINE';
const OT_EDIT_MACHINE                 = 'EDIT MACHINE';

const OT_MACHINE_QUANTITY_CHANGE                 = 'MACHINE QUANITY CHANGE';

//Operations Types - used for RFP history records
const OT_NEW_RFP                  = 'NEW RFP';
const OT_EDIT_RFP                 = 'EDIT RFP';
const OT_EDIT_RFP_WITH_ATTACHMENT                 = 'EDIT RFP WITH ATTACHMENT';
const OT_PO_CREATED                 = 'PO CREATED FROM RFP';

//Operations Types - used for PO history records
const OT_NEW_PO                  = 'NEW PO';
const OT_EDIT_PO                 = 'EDIT PO';
const OT_EDIT_PO_WITH_PAYMENT_ATTACHMENT    = 'EDIT PO WITH PAYMENT REFERENCE ATTACHMENT';
const OT_EDIT_PO_INVOICE_ATTACHMENT    = 'EDIT PO WITH SUPPLIER INVOICE ATTACHMENT';

//No Image Place Holders
const NO_IMAGE_SPARE_PART = 'no-image-sparepart.png';


//Page IDs
const QUOTATION_LIST  = 'QUOTATION_LIST';
const SPARE_PART_LIST = 'SPARE_PART_LIST';
const SPARE_PART_VIEW = 'SPARE_PART_VIEW';


// User Profile related
const PROFILE_PIC_FOLDER    = '/uploads/userprofile-images/';
const DEFAULT_PROFILE_IMAGE = 'default_avatar.png';

const WEBHOOK_SECRET_KEY = 'woocommerceWebHookSecret';

//Consultation Statuses
const CONSULTATION_PROPOSAL_STATUS_DRAFT = 'DRAFT';
const CONSULTATION_PROPOSAL_STATUS_NEW = 'NEW';
const CONSULTATION_PROPOSAL_STATUS_AWAITING_APPROVAL = 'AWAITING APPROVAL';
const CONSULTATION_PROPOSAL_STATUS_APPROVED = 'APPROVED';
const CONSULTATION_PROPOSAL_STATUS_REJECTED = 'REJECTED';
const CONSULTATION_PROPOSAL_STATUS_SENT_TO_CUSTOMER = 'SENT TO CUSTOMER';
const CONSULTATION_PROPOSAL_STATUS_CUSTOMER_ACCEPTED = 'CUSTOMER ACCEPTED';
const CONSULTATION_PROPOSAL_STATUS_CUSTOMER_REJECTED = 'CUSTOMER REJECTED';
const CONSULTATION_PROPOSAL_STATUS_CONFIRMED = 'CONFIRMED';
const CONSULTATION_PROPOSAL_STATUS_CANCELLED = 'CANCELLED';